name: CI Only

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest flake8 black

      - name: Auto-format with Black
        run: black --line-length 120 app.py model.py tests/

      - name: Lint
        run: flake8 . --max-line-length 120

      - name: Run tests
        run: pytest -q
